# **1. Perkenalan Dataset**

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset dapat diperoleh dari berbagai sumber, seperti public repositories (*Kaggle*, *UCI ML Repository*, *Open Data*) atau data primer yang Anda kumpulkan sendiri.

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.

In [ ]:
#Type your code here
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import matplotlib.pyplot as plt  # Tambahan untuk visualisasi di notebook
import seaborn as sns
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan

In [ ]:
#Type your code here
# Membaca file
nama_file = "dataset_penjualan_umkm_pondok_gede_2024_2025.xlsx"
df = pd.read_excel(nama_file)

# Menampilkan ukuran data
print(f"Total Baris: {df.shape[0]}, Total Kolom: {df.shape[1]}")
df.head()

Total Baris: 7233, Total Kolom: 11

,Invoice_ID,Tanggal,Nama_Produk,Kategori,Jumlah_Terjual,Harga_Satuan,Total_Penjualan,Metode_Pembayaran,Channel_Penjualan,Nama_Pelanggan,Wilayah
0,INV-1001,2024-01-01,Seblak Instan,Makanan,1,15253,15253,Transfer Bank,Shopee,"Vanya Nashiruddin, S.Pd",Pondok Gede
1,INV-1002,2024-01-01,Keripik Pisang,Snack,2,14467,28934,QRIS,Offline Store,Rini Januar,Pondok Gede
2,INV-1003,2024-01-01,Jus Alpukat,Minuman,1,16244,16244,QRIS,Shopee,Zulaikha Jailani,Pondok Gede
3,INV-1004,2024-01-01,Es Kopi Susu,Minuman,9,24931,224379,QRIS,Offline Store,"Hana Tampubolon, M.Pd",Pondok Gede
4,INV-1005,2024-01-01,Es Kopi Susu,Minuman,9,23436,210924,Transfer Bank,Instagram,Eja Sinaga,Pondok Gede

# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.

In [ ]:
#Type your code here
df.info()
# Pengecekan Statistik deskriptif
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7233 entries, 0 to 7232
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Invoice_ID         7233 non-null   object
 1   Tanggal            7233 non-null   object
 2   Nama_Produk        7233 non-null   object
 3   Kategori           7233 non-null   object
 4   Jumlah_Terjual     7233 non-null   int64
 5   Harga_Satuan       7233 non-null   int64
 6   Total_Penjualan    7233 non-null   int64
 7   Metode_Pembayaran  7233 non-null   object
 8   Channel_Penjualan  7233 non-null   object
 9   Nama_Pelanggan     7233 non-null   object
 10  Wilayah            7233 non-null   object
dtypes: int64(3), object(8)
memory usage: 621.7+ KB

       Jumlah_Terjual  Harga_Satuan  Total_Penjualan
count     7233.000000   7233.000000      7233.000000
mean         5.502143  21061.399696    115603.294760
std          2.855678   7567.236853     75732.884088
min          1.000000   8005.000000      8065.000000
25%          3.000000  15705.000000     56025.000000
50%          6.000000  19997.000000    102264.000000
75%          8.000000  25517.000000    161720.000000
max         10.000000  38000.000000    378810.000000

# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.

In [7]:
df_cleaned = df.copy()

# Hapus duplikat
df_cleaned.drop_duplicates(inplace=True)

for col in df_cleaned.columns:
        if df_cleaned[col].isnull().sum() > 0:
            if df_cleaned[col].dtype in ['int64', 'float64']:
                median_val = df_cleaned[col].median()
                df_cleaned[col] = df_cleaned[col].fillna(median_val)
            else:
                mode_val = df_cleaned[col].mode()[0]
                df_cleaned[col] = df_cleaned[col].fillna(mode_val)
print("Penanganan missing values selesai.")

if df_cleaned.duplicated().sum() > 0:
        initial_rows = df_cleaned.shape[0]
        df_cleaned.drop_duplicates(inplace=True)
        print(f"Berhasil menghapus {initial_rows - df_cleaned.shape[0]} baris duplikat.")
else:
  print("Tidak ditemukan data duplikat.")

# Feature engineering Tanggal
if 'Tanggal' in df_cleaned.columns:
    df_cleaned['Tanggal'] = pd.to_datetime(df_cleaned['Tanggal'])
    df_cleaned['Tahun'] = df_cleaned['Tanggal'].dt.year
    df_cleaned['Bulan'] = df_cleaned['Tanggal'].dt.month
    df_cleaned['Hari'] = df_cleaned['Tanggal'].dt.day

print("Data duplikat dihapus dan fitur tanggal telah diekstrak!")

# Capping outlier pada Total_Penjualan
Q1 = df_cleaned['Total_Penjualan'].quantile(0.25)
Q3 = df_cleaned['Total_Penjualan'].quantile(0.75)
IQR = Q3 - Q1
df_cleaned['Total_Penjualan'] = np.where(df_cleaned['Total_Penjualan'] > (Q3 + 1.5 * IQR), Q3 + 1.5 * IQR, df_cleaned['Total_Penjualan'])

# One-Hot Encoding
kolom_kategori = ['Kategori', 'Metode_Pembayaran', 'Channel_Penjualan']
df_siap_ml = pd.get_dummies(df_cleaned, columns=kolom_kategori, drop_first=True)

df_siap_ml.head()

if 'Total_Penjualan' in df_cleaned.columns:
        Q1 = df_cleaned['Total_Penjualan'].quantile(0.25)
        Q3 = df_cleaned['Total_Penjualan'].quantile(0.75)
        IQR = Q3 - Q1
        upper_bound = Q3 + 1.5 * IQR
        lower_bound = Q1 - 1.5 * IQR

        df_cleaned['Total_Penjualan'] = np.where(df_cleaned['Total_Penjualan'] > upper_bound, upper_bound, df_cleaned['Total_Penjualan'])
        df_cleaned['Total_Penjualan'] = np.where(df_cleaned['Total_Penjualan'] < lower_bound, lower_bound, df_cleaned['Total_Penjualan'])
        print("Outlier pada 'Total_Penjualan' telah di-capping.")

if 'Jumlah_Terjual' in df_cleaned.columns:
        bins = [0, 3, 7, float('inf')]
        labels = ['Sedikit', 'Sedang', 'Banyak']
        df_cleaned['Kategori_Volume'] = pd.cut(df_cleaned['Jumlah_Terjual'], bins=bins, labels=labels)
        print("Binning 'Jumlah_Terjual' ke 'Kategori_Volume' selesai.")

kolom_drop = ['Invoice_ID', 'Nama_Pelanggan', 'Nama_Produk', 'Wilayah', 'Tanggal']
kolom_drop_ready = [col for col in kolom_drop if col in df_cleaned.columns]
df_cleaned.drop(columns=kolom_drop_ready, inplace=True)

# Menentukan kolom kategori yang tersisa untuk di-encode
kolom_kategori = ['Kategori', 'Metode_Pembayaran', 'Channel_Penjualan', 'Kategori_Volume']
kolom_ready_to_encode = [col for col in kolom_kategori if col in df_cleaned.columns]

if kolom_ready_to_encode:
    df_cleaned = pd.get_dummies(df_cleaned, columns=kolom_ready_to_encode, drop_first=True)
    print(f"One-Hot Encoding selesai untuk {kolom_ready_to_encode}")

    fitur_numerik = ['Harga_Satuan', 'Jumlah_Terjual']
    fitur_numerik_ready = [col for col in fitur_numerik if col in df_cleaned.columns]

    if fitur_numerik_ready:
        scaler = StandardScaler()
        df_cleaned[fitur_numerik_ready] = scaler.fit_transform(df_cleaned[fitur_numerik_ready])
        print(f"Standarisasi (StandardScaler) selesai pada {fitur_numerik_ready}")

    print("Pipeline Selesai! \n")

Penanganan missing values selesai.
Tidak ditemukan data duplikat.
Data duplikat dihapus dan fitur tanggal telah diekstrak!
Outlier pada 'Total_Penjualan' telah di-capping.
Binning 'Jumlah_Terjual' ke 'Kategori_Volume' selesai.
One-Hot Encoding selesai untuk ['Kategori', 'Metode_Pembayaran', 'Channel_Penjualan', 'Kategori_Volume']
Standarisasi (StandardScaler) selesai pada ['Harga_Satuan', 'Jumlah_Terjual']
Pipeline Selesai!